export const SET_INSURANNCE_PROVIDER = 'SET_INSURANNCE_PROVIDER';
export const SET_INSURANNCE_PLAN = 'SET_INSURANNCE_PLAN';
export const SET_PROCEDURE = 'SET_PROCEDURE';
export const SET_ZIPCODE = 'SET_ZIPCODE';
export const SET_STEP = 'SET_STEP';
export const SET_RADIUS = 'SET_RADIUS';
export const SET_LAT_LON = 'SET_LAT_LON';
export const SET_LOCATION_TYPE = 'SET_LOCATION_TYPE';